openapi: '3.0.2'
info:
  title: Posts from JsonPlaceHolder
  version: '1.0'
servers:
  - url: https://api.server.test/v1
  - url: https://jsonplaceholder.typicode.com/
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
  /posts:
    get:
      responses:
        '200':
           description: posts from JsonPlace Holder API
           content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
           description: post inserted
           content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
           description:  type POST error
    put:
      parameters:
        - in: query
          name: id
          description: a unique post id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '200':
           description: post inserted
           content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
           description:  type POST error
components:
  schemas:
    Post:
      type: object
      required:
        - id
        - userId
        - title
        - body
      properties:
        id:
          type: integer
          example: 101
        userId:
          type: integer
          example: 2
        title:
          type: string
          example: 'title for a sample post'
        body:
          type: string
          example: 'body for a sample post.......  body for a sample post....... body for a sample post.......body for a sample post.......'
